### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Shougo** [wsdjeg/dein-ui.vim#1]
* `autoload/deinui/*.vim` instead of `autoload/SpaceVim/*.vim`

* `DeinUIUpdate` or `DeinUpdate` is better than `SPUpdate`.

* `SPUpdate` should be defined in SpaceVim configuration.

**Comment by Shougo** [comment]
> In order to automatically synchronize from upstream, we need to keep the file consistent.

Oh...

**Comment by wsdjeg** [comment]
when I update this script in SpaceVim, I hope this repo can be updated automatically.

**Comment by weilbith** [comment]
@Shougo this plugin also requires to set the _SpaceVim_ variable `g:spacevim_plugin_manager`, what's kinda ugly, if not using _SpaceVim_, to define the plugin manager to call its update function. Couldn't this be set to a default value that points to `dein.vim`?

**Comment by weilbith** [comment]
`g:spacevim_plugin_manager_max_processes` is also required. Afterwards I get the following error:

```vim
E475: Invalid argument: expecting valid directory
```

Too bad, that it is not usable without _SpaceVim_ liked the realtime feedback...

**Comment by wsdjeg** [comment]
Ok, This repo is still WIP, I should add this to README

**Comment by wsdjeg** [comment]
I have update the description

**Comment by Shougo** [comment]
> Couldn't this be set to a default value that points to dein.vim?

It cannot.
It should be fixed in dein-ui.vim plugin.

**Comment by weilbith** [comment]
@Shougo correct. 
I took a look into the code, but it doesn't look like it could be speparated from all the _SpaceVim_ staff that ez...

**Comment by wsdjeg** [comment]
I have add `DeinUpdate` command, and fix the spacevim options, It should works now.
