### ISSUE TITLE
popup or float windows?

### ISSUE THREAD

**Issue by Freed-Wu** [wsdjeg/dein-ui.vim#10]
can it support popup, float window?

thanks! it is an enhancement.

**Comment by wsdjeg** [comment]
https://github.com/SpaceVim/SpaceVim/blob/763045513d6227a59bdb2a3a772740c3be97ac01/autoload/SpaceVim/plugins/manager.vim#L605

I do not know when this line is added, but based on this line, you can change `g:spacevim_windows` to a `string`, which should be a `vim script` to open float window.

for example:

```
let g:spacevim_window = "call nvim_open_win(bufadd(''), v:true, {'relative' : 'win', 'row': 1, 'col': 3, 'width':&columns /2, 'height':&lines -4})"
```
