### ISSUE TITLE
Add section to docs about syntax highlighting apart from SpaceVim

### ISSUE THREAD

**Issue by unclechu** [wsdjeg/dein-ui.vim#4]
If you're (as me) using this plugin apart from SpaceVim then by default you have no syntax highlighting for `:DeinUpdate` window.

I personally solved it by copying `SpaceVimPlugManager` syntax module to my own vim config:
https://github.com/unclechu/neovimrc/blob/369e1bef97e372074fb13137f7507f138b6ba050/syntax/SpaceVimPlugManager.vim

How about to add this instructions to the README? I could make a PR but maybe you have a better solution to deliver this syntax highlighting?

**Comment by unclechu** [comment]
@wsdjeg Maybe if it's stated as:
> ... detached from SpaceVim`

It supposed to provide own syntax support?

**Comment by wsdjeg** [comment]
fixed by https://github.com/SpaceVim/SpaceVim/commit/c9e1d4c9635c483bb3334c00ed36026d18950070

**Comment by unclechu** [comment]
Now syntax is highlighted, cool, thanks!
